baseURL = "https://juliencloud1712.github.io/Arpege-solidaires-informatique/"
DefaultContentLanguage = "fr"
enableEmoji = true
enableRobotsTXT = true
languageCode = "fr-fr"
pygmentsCodefencesGuessSyntax = true
pygmentsCodeFences = true
pygmentsStyle = "trac"
pygmentsUseClasses = true
theme = "beautifulhugo"
title = "Arpège - Solidaires Informatique"


[params]
comments = false
commit = true
dateFormat = "02/01/2006"
delayDisqus = false
description = "Arpège - Solidaires Informatique"
disableMath = true
favicon = "img/logo_solidaires_carre.svg"
mainSections = ["posts"]
menu_item_separator = " · "
readingTime = false
rss = true
selfHosted = true
showRelatedPosts = false
SidebarRecentLimit = 5
socialShare = false
subtitle = ""
useHLJS = false
wordCount = false

  [params.author]
    name = "Julien"


[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true

[[menu.main]]
name = "Actualités"
url = "./"
weight = 1

[[menu.main]]
name = "Vos droits"
weight = 3
url = "page/vos_droits"

[[menu.main]]
name = "Contact"
weight = 9
url = "page/contact"


[markup.goldmark.renderer]
unsafe = true
